### ISSUE TITLE
Cellar data extraction

### ISSUE THREAD

**Issue by shashankmc** [maastrichtlawtech/case-law-explorer#10]
During extraction of cellar data, there are couple of issues - 
1. Bad gateway (occurs occasionally).
2. `urllib.error.HTTPError: HTTP Error 400: Bad Request` leads to `SPARQLWrapper.SPARQLExceptions.QueryBadFormed: QueryBadFormed: A bad request has been sent to the endpoint: probably the SPARQL query is badly formed.`

**Comment by pranavnbapat** [comment]
Setting the method as POST of SPARQL in the get_raw_cellar_metadata method of the data_extraction.py file seems to be not causing this issue anymore.

Add
sparql.setMethod(POST)

after
sparql.setReturnFormat(JSON)

And import POST from SPARQLWrapper

**Comment by shashankmc** [comment]
Can we also consider connectivity disruption during extraction? (Start downloading midway rather than all over again?)
