### ISSUE TITLE
Data loading of full-text data

### ISSUE THREAD

**Issue by running-machin** [maastrichtlawtech/case-law-explorer#22]
While loading the transformed data to DynamoDB, I have come across certain limits items [https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#limits-items](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ServiceQuotas.html#limits-items) Some of the full-text data may exceed this limit, for example for _ecli_ `ECLI:EU:C:2021:724` in cellar full-text data exceed 400kb(406KB exactly). 

What should be the best way to proceed?

**Comment by running-machin** [comment]
I came across this in documentation [https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-use-s3-too.html](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-use-s3-too.html)

**Comment by shashankmc** [comment]
Resolved by storing full text files in S3 bucket.
