### ISSUE TITLE
rechtspraak archive link seems to be dead

### ISSUE THREAD

**Issue by ELotfi** [maastrichtlawtech/case-law-explorer#27]
Hi 
The rechtspraak archive link (http://static.rechtspraak.nl/PI/OpenDataUitspraken.zip) seems to be dead. Is there any alternative to get the data?

**Comment by shashankmc** [comment]
@ELotfi I don't think that's supported anymore. We have moved to downloading on the API made available which can be accessed through a python package developed here - https://github.com/maastrichtlawtech/extraction_libraries/tree/rechtspraak 

The API documentation is available here - https://www.rechtspraak.nl/SiteCollectionDocuments/Technische-documentatie-Open-Data-van-de-Rechtspraak.pdf

**Comment by shashankmc** [comment]
Closing the issue as its related to Rechtspraak and not case law explorer.
