### ISSUE TITLE
Some issues with rechtspraak_dump_downloader

### ISSUE THREAD

**Issue by odinson394** [maastrichtlawtech/case-law-explorer#4]
Hi, 

I've been trying to get the  rechtspraak_dump_downloader working. After changing some minor typos/problems which were easy for me to find in the code , I have now gotten stuck. For reference, the typos were:

### Typos

> 1. Error in print command due to typo
>   File "rechtspraak_dump_downloader.py", line 42
>     print(**_f_**"\nUpdating {args.storage} storage ...")
> 

-removed the f

2. Error in print command due to variable rs_url not being a string:

> Traceback (most recent call last):
>   File "/Users/jeanquinto/Documents/Projects/AI Law/case-law-explorer/data_extraction/caselaw/rechtspraak/rechtspraak_dump_downloader.py", line 37, in <module>
>     print("Downloading Rechtspraak.nl dump - " + date + " - " + rs_url + " ...")
> TypeError: can only concatenate str (not "NoneType") to str

Altered code to read:
print("Downloading Rechtspraak.nl dump - " + date + " - " + _**str(rs_url)**_ + " ...")

### Current issue
However, having resolved that in the simplest way I could think of,  I seem to be stuck with an error that also seems related to rs_url not being a string, or somehow a wrong type: 

> Traceback (most recent call last):
>   File "/Users/jeanquinto/Documents/Projects/AI Law/case-law-explorer/data_extraction/caselaw/rechtspraak/rechtspraak_dump_downloader.py", line 40, in <module>
>     urllib.request.urlretrieve(rs_url, output_path)
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 237, in urlretrieve
>     url_type, path = _splittype(url)
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/parse.py", line 1040, in _splittype
>     match = _typeprog.match(url)
> TypeError: expected string or bytes-like object
> 

Creating a new rs_url variable formatted as a string and passing that to urllib.request.urlretrieve only threw more errors:

>  File "/Users/jeanquinto/Documents/Projects/AI Law/case-law-explorer/data_extraction/caselaw/rechtspraak/rechtspraak_dump_downloader.py", line 40, in <module>
>   urllib.request.urlretrieve(rs_urlstring, output_path)
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 239, in urlretrieve
>     with contextlib.closing(urlopen(url, data)) as fp:
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 501, in open
>     req = Request(fullurl, data)
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 320, in __init__
>     self.full_url = url
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 346, in full_url
>     self._parse()
>   File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 375, in _parse
>     raise ValueError("unknown url type: %r" % self.full_url)
> ValueError: unknown url type: 'None'

I have been trying to figure it out but honestly quite out of my depth here. It seems that rs_url is not being populated properly, because if I print it, it reads 'None'. However, I am unsure how to alter:

> if getenv('SAMPLE_TEST') == 'TRUE':
>     rs_url = getenv('URL_RS_ARCHIVE_SAMPLE')
> else:
>     rs_url = 
> getenv('URL_RS_ARCHIVE')

I tried searching the other documents from 'URL_RS-ARCHIVE' but didn't turn anything up. 

So thought I would check-in and see if there is a simple fix I can try (like just passing whatever URL you are trying to get in there?). I am using python 3.9.7 on MacOs (M1).

**Comment by shashankmc** [comment]
The `.env` file is stored as [.env.example](https://github.com/maastrichtlawtech/case-law-explorer/blob/fdce88f143302493a37cd350b807206ee6ee7a40/.env.example) which likely is the reason for this error. After having made a copy of the example file to `.env`, the issue seems to be resolved. This needs to be validated to see if additional conflicts occur for other extractions (most likely not). I think the AWS deployment of this might not be seeing this issue.

**Comment by pranavnbapat** [comment]
> The `.env` file is stored as [.env.example](https://github.com/maastrichtlawtech/case-law-explorer/blob/fdce88f143302493a37cd350b807206ee6ee7a40/.env.example) which likely is the reason for this error. After having made a copy of the example file to `.env`, the issue seems to be resolved. This needs to be validated to see if additional conflicts occur for other extractions (most likely not). I think the AWS deployment of this might not be seeing this issue.

Renaming to .env seems working fine. I ran the script 3 times and didn't give any errors. I also ran the code in Colab by only considering the required code and ignoring the print formatting, and it worked fine as well.
