### ISSUE TITLE
Automate ETL pipeline

### ISSUE THREAD

**Issue by maxin-e** [maastrichtlawtech/case-law-explorer#8]
Use framework for automating the ETL pipeline and running scheduled updates (consider [AWS Data Pipeline](https://aws.amazon.com/datapipeline/), [Apache Airflow](https://airflow.apache.org/), [Luigi](https://luigi.readthedocs.io/en/stable/)).

Replace:
- [storage_handler.py](https://github.com/maastrichtlawtech/case-law-explorer/blob/master/definitions/storage_handler.py) functionality
- Intermediate steps of reading and writing to CSV
- Rechtspraak bulk download (in [rechtspraak_dump_downloader.py](https://github.com/maastrichtlawtech/case-law-explorer/blob/master/data_extraction/caselaw/rechtspraak/rechtspraak_dump_downloader.py)): use [Rechtspraak API](https://www.rechtspraak.nl/Uitspraken/paginas/open-data.aspx) instead

**Comment by shashankmc** [comment]
Done with the below two tasks.

- Intermediate steps of reading and writing to CSV
- Rechtspraak bulk download (in [rechtspraak_dump_downloader.py](https://github.com/maastrichtlawtech/case-law-explorer/blob/master/data_extraction/caselaw/rechtspraak/rechtspraak_dump_downloader.py)): use [Rechtspraak API](https://www.rechtspraak.nl/Uitspraken/paginas/open-data.aspx) instead

Creating new issue #23  for storage_handler replacement.
