### ISSUE TITLE
Validation of ECHR_Metadata.csv file

### ISSUE THREAD

**Issue by shashankmc** [maastrichtlawtech/case-law-explorer#9]
While the ECHR data is extracted successfully, it fails to save to the csv file in https://github.com/maastrichtlawtech/case-law-explorer/blob/5ad4450feebe655dbd0a89209af900d0dd2abc08/data_extraction/caselaw/echr/ECHR_metadata_harvester.py#L188

**Comment by pranavnbapat** [comment]
echr folder doesn't exist in the data folder. to_csv method won't create a folder if it doesn't exist. Thus, it is failing.
